[package]
name = "jambrush"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
edition = "2018"

[dependencies]
gfx-hal = "~0.1.0"
gfx-backend-gl = "~0.1.0"
image = "~0.20.0"
texture_packer = "~0.15.0"
winit = "~0.18.0"

[dependencies.rusttype]
version = "~0.7.2"
features = ["gpu_cache"]

[dependencies.backend]
package = "gfx-backend-metal"
version = "~0.1.0"

[build-dependencies]
glsl-to-spirv = "~0.1.6"
