[package]
name = "jambrush"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
edition = "2018"

[dependencies]
image = "~0.20.0"
texture_packer = "~0.15.0"
winit = "~0.17.2"

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"

[dependencies.backend]
git = "https://github.com/gfx-rs/gfx"
package = "gfx-backend-metal"

[dependencies.rusttype]
version = "~0.7.2"
features = ["gpu_cache"]

[build-dependencies]
glsl-to-spirv = "~0.1.6"
